/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Defines AlertUrgency
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AlertUrgency
    {
        /// <summary>
        /// Enum Immediate for value: Immediate
        /// </summary>
        [EnumMember(Value = "Immediate")]
        Immediate = 1,

        /// <summary>
        /// Enum Expected for value: Expected
        /// </summary>
        [EnumMember(Value = "Expected")]
        Expected = 2,

        /// <summary>
        /// Enum Future for value: Future
        /// </summary>
        [EnumMember(Value = "Future")]
        Future = 3,

        /// <summary>
        /// Enum Past for value: Past
        /// </summary>
        [EnumMember(Value = "Past")]
        Past = 4,

        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 5
    }

}
