/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Defines AlertCertainty
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AlertCertainty
    {
        /// <summary>
        /// Enum Observed for value: Observed
        /// </summary>
        [EnumMember(Value = "Observed")]
        Observed = 1,

        /// <summary>
        /// Enum Likely for value: Likely
        /// </summary>
        [EnumMember(Value = "Likely")]
        Likely = 2,

        /// <summary>
        /// Enum Possible for value: Possible
        /// </summary>
        [EnumMember(Value = "Possible")]
        Possible = 3,

        /// <summary>
        /// Enum Unlikely for value: Unlikely
        /// </summary>
        [EnumMember(Value = "Unlikely")]
        Unlikely = 4,

        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 5
    }

}
