/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Glossary200Response
    /// </summary>
    [DataContract(Name = "glossary_200_response")]
    public partial class Glossary200Response : IEquatable<Glossary200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Glossary200Response" /> class.
        /// </summary>
        /// <param name="context">context.</param>
        /// <param name="glossary">A list of glossary terms.</param>
        public Glossary200Response(JsonLdContext context = default(JsonLdContext), List<Glossary200ResponseGlossaryInner> glossary = default(List<Glossary200ResponseGlossaryInner>))
        {
            this.Context = context;
            this.Glossary = glossary;
        }

        /// <summary>
        /// Gets or Sets Context
        /// </summary>
        [DataMember(Name = "@context", EmitDefaultValue = false)]
        public JsonLdContext Context { get; set; }

        /// <summary>
        /// A list of glossary terms
        /// </summary>
        /// <value>A list of glossary terms</value>
        [DataMember(Name = "glossary", EmitDefaultValue = false)]
        public List<Glossary200ResponseGlossaryInner> Glossary { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Glossary200Response {\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("  Glossary: ").Append(Glossary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Glossary200Response);
        }

        /// <summary>
        /// Returns true if Glossary200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of Glossary200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Glossary200Response input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Context == input.Context ||
                    (this.Context != null &&
                    this.Context.Equals(input.Context))
                ) && 
                (
                    this.Glossary == input.Glossary ||
                    this.Glossary != null &&
                    input.Glossary != null &&
                    this.Glossary.SequenceEqual(input.Glossary)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Context != null)
                {
                    hashCode = (hashCode * 59) + this.Context.GetHashCode();
                }
                if (this.Glossary != null)
                {
                    hashCode = (hashCode * 59) + this.Glossary.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
