/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Denotes the units used in the textual portions of the forecast.
    /// </summary>
    /// <value>Denotes the units used in the textual portions of the forecast.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GridpointForecastUnits
    {
        /// <summary>
        /// Enum Us for value: us
        /// </summary>
        [EnumMember(Value = "us")]
        Us = 1,

        /// <summary>
        /// Enum Si for value: si
        /// </summary>
        [EnumMember(Value = "si")]
        Si = 2
    }

}
