/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// IconsSummary200Response
    /// </summary>
    [DataContract(Name = "icons_summary_200_response")]
    public partial class IconsSummary200Response : IEquatable<IconsSummary200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IconsSummary200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IconsSummary200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IconsSummary200Response" /> class.
        /// </summary>
        /// <param name="context">context.</param>
        /// <param name="icons">icons (required).</param>
        public IconsSummary200Response(JsonLdContext context = default(JsonLdContext), Dictionary<string, IconsSummary200ResponseIconsValue> icons = default(Dictionary<string, IconsSummary200ResponseIconsValue>))
        {
            // to ensure "icons" is required (not null)
            if (icons == null)
            {
                throw new ArgumentNullException("icons is a required property for IconsSummary200Response and cannot be null");
            }
            this.Icons = icons;
            this.Context = context;
        }

        /// <summary>
        /// Gets or Sets Context
        /// </summary>
        [DataMember(Name = "@context", EmitDefaultValue = false)]
        public JsonLdContext Context { get; set; }

        /// <summary>
        /// Gets or Sets Icons
        /// </summary>
        [DataMember(Name = "icons", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, IconsSummary200ResponseIconsValue> Icons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IconsSummary200Response {\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("  Icons: ").Append(Icons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IconsSummary200Response);
        }

        /// <summary>
        /// Returns true if IconsSummary200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of IconsSummary200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IconsSummary200Response input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Context == input.Context ||
                    (this.Context != null &&
                    this.Context.Equals(input.Context))
                ) && 
                (
                    this.Icons == input.Icons ||
                    this.Icons != null &&
                    input.Icons != null &&
                    this.Icons.SequenceEqual(input.Icons)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Context != null)
                {
                    hashCode = (hashCode * 59) + this.Context.GetHashCode();
                }
                if (this.Icons != null)
                {
                    hashCode = (hashCode * 59) + this.Icons.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
