/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Marine region code. These are groups of marine areas combined. * AL: Alaska waters (PK) * AT: Atlantic Ocean (AM, AN) * GL: Great Lakes (LC, LE, LH, LM, LO, LS, SL) * GM: Gulf of Mexico (GM) * PA: Eastern Pacific Ocean and U.S. West Coast (PZ) * PI: Central and Western Pacific (PH, PM, PS) 
    /// </summary>
    /// <value>Marine region code. These are groups of marine areas combined. * AL: Alaska waters (PK) * AT: Atlantic Ocean (AM, AN) * GL: Great Lakes (LC, LE, LH, LM, LO, LS, SL) * GM: Gulf of Mexico (GM) * PA: Eastern Pacific Ocean and U.S. West Coast (PZ) * PI: Central and Western Pacific (PH, PM, PS) </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MarineRegionCode
    {
        /// <summary>
        /// Enum AL for value: AL
        /// </summary>
        [EnumMember(Value = "AL")]
        AL = 1,

        /// <summary>
        /// Enum AT for value: AT
        /// </summary>
        [EnumMember(Value = "AT")]
        AT = 2,

        /// <summary>
        /// Enum GL for value: GL
        /// </summary>
        [EnumMember(Value = "GL")]
        GL = 3,

        /// <summary>
        /// Enum GM for value: GM
        /// </summary>
        [EnumMember(Value = "GM")]
        GM = 4,

        /// <summary>
        /// Enum PA for value: PA
        /// </summary>
        [EnumMember(Value = "PA")]
        PA = 5,

        /// <summary>
        /// Enum PI for value: PI
        /// </summary>
        [EnumMember(Value = "PI")]
        PI = 6
    }

}
