/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Marine area code as defined in NWS Directive 10-302: * AM: Western North Atlantic Ocean and along U.S. East Coast south of Currituck Beach Light NC following the coastline into Gulf of Mexico to Ocean Reef FL including the Caribbean * AN: Western North Atlantic Ocean and along U.S. East Coast from Canadian border south to Currituck Beach Light NC * GM: Gulf of Mexico and along the U.S. Gulf Coast from the Mexican border to Ocean Reef FL * LC: Lake St. Clair * LE: Lake Erie * LH: Lake Huron * LM: Lake Michigan * LO: Lake Ontario * LS: Lake Superior * PH: Central Pacific Ocean including Hawaiian waters * PK: North Pacific Ocean near Alaska and along Alaska coastline including the Bering Sea and the Gulf of Alaska * PM: Western Pacific Ocean including Mariana Island waters * PS: South Central Pacific Ocean including American Samoa waters * PZ: Eastern North Pacific Ocean and along U.S. West Coast from Canadian border to Mexican border * SL: St. Lawrence River above St. Regis 
    /// </summary>
    /// <value>Marine area code as defined in NWS Directive 10-302: * AM: Western North Atlantic Ocean and along U.S. East Coast south of Currituck Beach Light NC following the coastline into Gulf of Mexico to Ocean Reef FL including the Caribbean * AN: Western North Atlantic Ocean and along U.S. East Coast from Canadian border south to Currituck Beach Light NC * GM: Gulf of Mexico and along the U.S. Gulf Coast from the Mexican border to Ocean Reef FL * LC: Lake St. Clair * LE: Lake Erie * LH: Lake Huron * LM: Lake Michigan * LO: Lake Ontario * LS: Lake Superior * PH: Central Pacific Ocean including Hawaiian waters * PK: North Pacific Ocean near Alaska and along Alaska coastline including the Bering Sea and the Gulf of Alaska * PM: Western Pacific Ocean including Mariana Island waters * PS: South Central Pacific Ocean including American Samoa waters * PZ: Eastern North Pacific Ocean and along U.S. West Coast from Canadian border to Mexican border * SL: St. Lawrence River above St. Regis </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MarineAreaCode
    {
        /// <summary>
        /// Enum AM for value: AM
        /// </summary>
        [EnumMember(Value = "AM")]
        AM = 1,

        /// <summary>
        /// Enum AN for value: AN
        /// </summary>
        [EnumMember(Value = "AN")]
        AN = 2,

        /// <summary>
        /// Enum GM for value: GM
        /// </summary>
        [EnumMember(Value = "GM")]
        GM = 3,

        /// <summary>
        /// Enum LC for value: LC
        /// </summary>
        [EnumMember(Value = "LC")]
        LC = 4,

        /// <summary>
        /// Enum LE for value: LE
        /// </summary>
        [EnumMember(Value = "LE")]
        LE = 5,

        /// <summary>
        /// Enum LH for value: LH
        /// </summary>
        [EnumMember(Value = "LH")]
        LH = 6,

        /// <summary>
        /// Enum LM for value: LM
        /// </summary>
        [EnumMember(Value = "LM")]
        LM = 7,

        /// <summary>
        /// Enum LO for value: LO
        /// </summary>
        [EnumMember(Value = "LO")]
        LO = 8,

        /// <summary>
        /// Enum LS for value: LS
        /// </summary>
        [EnumMember(Value = "LS")]
        LS = 9,

        /// <summary>
        /// Enum PH for value: PH
        /// </summary>
        [EnumMember(Value = "PH")]
        PH = 10,

        /// <summary>
        /// Enum PK for value: PK
        /// </summary>
        [EnumMember(Value = "PK")]
        PK = 11,

        /// <summary>
        /// Enum PM for value: PM
        /// </summary>
        [EnumMember(Value = "PM")]
        PM = 12,

        /// <summary>
        /// Enum PS for value: PS
        /// </summary>
        [EnumMember(Value = "PS")]
        PS = 13,

        /// <summary>
        /// Enum PZ for value: PZ
        /// </summary>
        [EnumMember(Value = "PZ")]
        PZ = 14,

        /// <summary>
        /// Enum SL for value: SL
        /// </summary>
        [EnumMember(Value = "SL")]
        SL = 15
    }

}
