/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Three-letter identifier for a Center Weather Service Unit (CWSU).
    /// </summary>
    /// <value>Three-letter identifier for a Center Weather Service Unit (CWSU).</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NWSCenterWeatherServiceUnitId
    {
        /// <summary>
        /// Enum ZAB for value: ZAB
        /// </summary>
        [EnumMember(Value = "ZAB")]
        ZAB = 1,

        /// <summary>
        /// Enum ZAN for value: ZAN
        /// </summary>
        [EnumMember(Value = "ZAN")]
        ZAN = 2,

        /// <summary>
        /// Enum ZAU for value: ZAU
        /// </summary>
        [EnumMember(Value = "ZAU")]
        ZAU = 3,

        /// <summary>
        /// Enum ZBW for value: ZBW
        /// </summary>
        [EnumMember(Value = "ZBW")]
        ZBW = 4,

        /// <summary>
        /// Enum ZDC for value: ZDC
        /// </summary>
        [EnumMember(Value = "ZDC")]
        ZDC = 5,

        /// <summary>
        /// Enum ZDV for value: ZDV
        /// </summary>
        [EnumMember(Value = "ZDV")]
        ZDV = 6,

        /// <summary>
        /// Enum ZFA for value: ZFA
        /// </summary>
        [EnumMember(Value = "ZFA")]
        ZFA = 7,

        /// <summary>
        /// Enum ZFW for value: ZFW
        /// </summary>
        [EnumMember(Value = "ZFW")]
        ZFW = 8,

        /// <summary>
        /// Enum ZHU for value: ZHU
        /// </summary>
        [EnumMember(Value = "ZHU")]
        ZHU = 9,

        /// <summary>
        /// Enum ZID for value: ZID
        /// </summary>
        [EnumMember(Value = "ZID")]
        ZID = 10,

        /// <summary>
        /// Enum ZJX for value: ZJX
        /// </summary>
        [EnumMember(Value = "ZJX")]
        ZJX = 11,

        /// <summary>
        /// Enum ZKC for value: ZKC
        /// </summary>
        [EnumMember(Value = "ZKC")]
        ZKC = 12,

        /// <summary>
        /// Enum ZLA for value: ZLA
        /// </summary>
        [EnumMember(Value = "ZLA")]
        ZLA = 13,

        /// <summary>
        /// Enum ZLC for value: ZLC
        /// </summary>
        [EnumMember(Value = "ZLC")]
        ZLC = 14,

        /// <summary>
        /// Enum ZMA for value: ZMA
        /// </summary>
        [EnumMember(Value = "ZMA")]
        ZMA = 15,

        /// <summary>
        /// Enum ZME for value: ZME
        /// </summary>
        [EnumMember(Value = "ZME")]
        ZME = 16,

        /// <summary>
        /// Enum ZMP for value: ZMP
        /// </summary>
        [EnumMember(Value = "ZMP")]
        ZMP = 17,

        /// <summary>
        /// Enum ZNY for value: ZNY
        /// </summary>
        [EnumMember(Value = "ZNY")]
        ZNY = 18,

        /// <summary>
        /// Enum ZOA for value: ZOA
        /// </summary>
        [EnumMember(Value = "ZOA")]
        ZOA = 19,

        /// <summary>
        /// Enum ZOB for value: ZOB
        /// </summary>
        [EnumMember(Value = "ZOB")]
        ZOB = 20,

        /// <summary>
        /// Enum ZSE for value: ZSE
        /// </summary>
        [EnumMember(Value = "ZSE")]
        ZSE = 21,

        /// <summary>
        /// Enum ZTL for value: ZTL
        /// </summary>
        [EnumMember(Value = "ZTL")]
        ZTL = 22
    }

}
