/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Three-letter identifier for a NWS office.
    /// </summary>
    /// <value>Three-letter identifier for a NWS office.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NWSForecastOfficeId
    {
        /// <summary>
        /// Enum AKQ for value: AKQ
        /// </summary>
        [EnumMember(Value = "AKQ")]
        AKQ = 1,

        /// <summary>
        /// Enum ALY for value: ALY
        /// </summary>
        [EnumMember(Value = "ALY")]
        ALY = 2,

        /// <summary>
        /// Enum BGM for value: BGM
        /// </summary>
        [EnumMember(Value = "BGM")]
        BGM = 3,

        /// <summary>
        /// Enum BOX for value: BOX
        /// </summary>
        [EnumMember(Value = "BOX")]
        BOX = 4,

        /// <summary>
        /// Enum BTV for value: BTV
        /// </summary>
        [EnumMember(Value = "BTV")]
        BTV = 5,

        /// <summary>
        /// Enum BUF for value: BUF
        /// </summary>
        [EnumMember(Value = "BUF")]
        BUF = 6,

        /// <summary>
        /// Enum CAE for value: CAE
        /// </summary>
        [EnumMember(Value = "CAE")]
        CAE = 7,

        /// <summary>
        /// Enum CAR for value: CAR
        /// </summary>
        [EnumMember(Value = "CAR")]
        CAR = 8,

        /// <summary>
        /// Enum CHS for value: CHS
        /// </summary>
        [EnumMember(Value = "CHS")]
        CHS = 9,

        /// <summary>
        /// Enum CLE for value: CLE
        /// </summary>
        [EnumMember(Value = "CLE")]
        CLE = 10,

        /// <summary>
        /// Enum CTP for value: CTP
        /// </summary>
        [EnumMember(Value = "CTP")]
        CTP = 11,

        /// <summary>
        /// Enum GSP for value: GSP
        /// </summary>
        [EnumMember(Value = "GSP")]
        GSP = 12,

        /// <summary>
        /// Enum GYX for value: GYX
        /// </summary>
        [EnumMember(Value = "GYX")]
        GYX = 13,

        /// <summary>
        /// Enum ILM for value: ILM
        /// </summary>
        [EnumMember(Value = "ILM")]
        ILM = 14,

        /// <summary>
        /// Enum ILN for value: ILN
        /// </summary>
        [EnumMember(Value = "ILN")]
        ILN = 15,

        /// <summary>
        /// Enum LWX for value: LWX
        /// </summary>
        [EnumMember(Value = "LWX")]
        LWX = 16,

        /// <summary>
        /// Enum MHX for value: MHX
        /// </summary>
        [EnumMember(Value = "MHX")]
        MHX = 17,

        /// <summary>
        /// Enum OKX for value: OKX
        /// </summary>
        [EnumMember(Value = "OKX")]
        OKX = 18,

        /// <summary>
        /// Enum PBZ for value: PBZ
        /// </summary>
        [EnumMember(Value = "PBZ")]
        PBZ = 19,

        /// <summary>
        /// Enum PHI for value: PHI
        /// </summary>
        [EnumMember(Value = "PHI")]
        PHI = 20,

        /// <summary>
        /// Enum RAH for value: RAH
        /// </summary>
        [EnumMember(Value = "RAH")]
        RAH = 21,

        /// <summary>
        /// Enum RLX for value: RLX
        /// </summary>
        [EnumMember(Value = "RLX")]
        RLX = 22,

        /// <summary>
        /// Enum RNK for value: RNK
        /// </summary>
        [EnumMember(Value = "RNK")]
        RNK = 23,

        /// <summary>
        /// Enum ABQ for value: ABQ
        /// </summary>
        [EnumMember(Value = "ABQ")]
        ABQ = 24,

        /// <summary>
        /// Enum AMA for value: AMA
        /// </summary>
        [EnumMember(Value = "AMA")]
        AMA = 25,

        /// <summary>
        /// Enum BMX for value: BMX
        /// </summary>
        [EnumMember(Value = "BMX")]
        BMX = 26,

        /// <summary>
        /// Enum BRO for value: BRO
        /// </summary>
        [EnumMember(Value = "BRO")]
        BRO = 27,

        /// <summary>
        /// Enum CRP for value: CRP
        /// </summary>
        [EnumMember(Value = "CRP")]
        CRP = 28,

        /// <summary>
        /// Enum EPZ for value: EPZ
        /// </summary>
        [EnumMember(Value = "EPZ")]
        EPZ = 29,

        /// <summary>
        /// Enum EWX for value: EWX
        /// </summary>
        [EnumMember(Value = "EWX")]
        EWX = 30,

        /// <summary>
        /// Enum FFC for value: FFC
        /// </summary>
        [EnumMember(Value = "FFC")]
        FFC = 31,

        /// <summary>
        /// Enum FWD for value: FWD
        /// </summary>
        [EnumMember(Value = "FWD")]
        FWD = 32,

        /// <summary>
        /// Enum HGX for value: HGX
        /// </summary>
        [EnumMember(Value = "HGX")]
        HGX = 33,

        /// <summary>
        /// Enum HUN for value: HUN
        /// </summary>
        [EnumMember(Value = "HUN")]
        HUN = 34,

        /// <summary>
        /// Enum JAN for value: JAN
        /// </summary>
        [EnumMember(Value = "JAN")]
        JAN = 35,

        /// <summary>
        /// Enum JAX for value: JAX
        /// </summary>
        [EnumMember(Value = "JAX")]
        JAX = 36,

        /// <summary>
        /// Enum KEY for value: KEY
        /// </summary>
        [EnumMember(Value = "KEY")]
        KEY = 37,

        /// <summary>
        /// Enum LCH for value: LCH
        /// </summary>
        [EnumMember(Value = "LCH")]
        LCH = 38,

        /// <summary>
        /// Enum LIX for value: LIX
        /// </summary>
        [EnumMember(Value = "LIX")]
        LIX = 39,

        /// <summary>
        /// Enum LUB for value: LUB
        /// </summary>
        [EnumMember(Value = "LUB")]
        LUB = 40,

        /// <summary>
        /// Enum LZK for value: LZK
        /// </summary>
        [EnumMember(Value = "LZK")]
        LZK = 41,

        /// <summary>
        /// Enum MAF for value: MAF
        /// </summary>
        [EnumMember(Value = "MAF")]
        MAF = 42,

        /// <summary>
        /// Enum MEG for value: MEG
        /// </summary>
        [EnumMember(Value = "MEG")]
        MEG = 43,

        /// <summary>
        /// Enum MFL for value: MFL
        /// </summary>
        [EnumMember(Value = "MFL")]
        MFL = 44,

        /// <summary>
        /// Enum MLB for value: MLB
        /// </summary>
        [EnumMember(Value = "MLB")]
        MLB = 45,

        /// <summary>
        /// Enum MOB for value: MOB
        /// </summary>
        [EnumMember(Value = "MOB")]
        MOB = 46,

        /// <summary>
        /// Enum MRX for value: MRX
        /// </summary>
        [EnumMember(Value = "MRX")]
        MRX = 47,

        /// <summary>
        /// Enum OHX for value: OHX
        /// </summary>
        [EnumMember(Value = "OHX")]
        OHX = 48,

        /// <summary>
        /// Enum OUN for value: OUN
        /// </summary>
        [EnumMember(Value = "OUN")]
        OUN = 49,

        /// <summary>
        /// Enum SHV for value: SHV
        /// </summary>
        [EnumMember(Value = "SHV")]
        SHV = 50,

        /// <summary>
        /// Enum SJT for value: SJT
        /// </summary>
        [EnumMember(Value = "SJT")]
        SJT = 51,

        /// <summary>
        /// Enum SJU for value: SJU
        /// </summary>
        [EnumMember(Value = "SJU")]
        SJU = 52,

        /// <summary>
        /// Enum TAE for value: TAE
        /// </summary>
        [EnumMember(Value = "TAE")]
        TAE = 53,

        /// <summary>
        /// Enum TBW for value: TBW
        /// </summary>
        [EnumMember(Value = "TBW")]
        TBW = 54,

        /// <summary>
        /// Enum TSA for value: TSA
        /// </summary>
        [EnumMember(Value = "TSA")]
        TSA = 55,

        /// <summary>
        /// Enum ABR for value: ABR
        /// </summary>
        [EnumMember(Value = "ABR")]
        ABR = 56,

        /// <summary>
        /// Enum APX for value: APX
        /// </summary>
        [EnumMember(Value = "APX")]
        APX = 57,

        /// <summary>
        /// Enum ARX for value: ARX
        /// </summary>
        [EnumMember(Value = "ARX")]
        ARX = 58,

        /// <summary>
        /// Enum BIS for value: BIS
        /// </summary>
        [EnumMember(Value = "BIS")]
        BIS = 59,

        /// <summary>
        /// Enum BOU for value: BOU
        /// </summary>
        [EnumMember(Value = "BOU")]
        BOU = 60,

        /// <summary>
        /// Enum CYS for value: CYS
        /// </summary>
        [EnumMember(Value = "CYS")]
        CYS = 61,

        /// <summary>
        /// Enum DDC for value: DDC
        /// </summary>
        [EnumMember(Value = "DDC")]
        DDC = 62,

        /// <summary>
        /// Enum DLH for value: DLH
        /// </summary>
        [EnumMember(Value = "DLH")]
        DLH = 63,

        /// <summary>
        /// Enum DMX for value: DMX
        /// </summary>
        [EnumMember(Value = "DMX")]
        DMX = 64,

        /// <summary>
        /// Enum DTX for value: DTX
        /// </summary>
        [EnumMember(Value = "DTX")]
        DTX = 65,

        /// <summary>
        /// Enum DVN for value: DVN
        /// </summary>
        [EnumMember(Value = "DVN")]
        DVN = 66,

        /// <summary>
        /// Enum EAX for value: EAX
        /// </summary>
        [EnumMember(Value = "EAX")]
        EAX = 67,

        /// <summary>
        /// Enum FGF for value: FGF
        /// </summary>
        [EnumMember(Value = "FGF")]
        FGF = 68,

        /// <summary>
        /// Enum FSD for value: FSD
        /// </summary>
        [EnumMember(Value = "FSD")]
        FSD = 69,

        /// <summary>
        /// Enum GID for value: GID
        /// </summary>
        [EnumMember(Value = "GID")]
        GID = 70,

        /// <summary>
        /// Enum GJT for value: GJT
        /// </summary>
        [EnumMember(Value = "GJT")]
        GJT = 71,

        /// <summary>
        /// Enum GLD for value: GLD
        /// </summary>
        [EnumMember(Value = "GLD")]
        GLD = 72,

        /// <summary>
        /// Enum GRB for value: GRB
        /// </summary>
        [EnumMember(Value = "GRB")]
        GRB = 73,

        /// <summary>
        /// Enum GRR for value: GRR
        /// </summary>
        [EnumMember(Value = "GRR")]
        GRR = 74,

        /// <summary>
        /// Enum ICT for value: ICT
        /// </summary>
        [EnumMember(Value = "ICT")]
        ICT = 75,

        /// <summary>
        /// Enum ILX for value: ILX
        /// </summary>
        [EnumMember(Value = "ILX")]
        ILX = 76,

        /// <summary>
        /// Enum IND for value: IND
        /// </summary>
        [EnumMember(Value = "IND")]
        IND = 77,

        /// <summary>
        /// Enum IWX for value: IWX
        /// </summary>
        [EnumMember(Value = "IWX")]
        IWX = 78,

        /// <summary>
        /// Enum JKL for value: JKL
        /// </summary>
        [EnumMember(Value = "JKL")]
        JKL = 79,

        /// <summary>
        /// Enum LBF for value: LBF
        /// </summary>
        [EnumMember(Value = "LBF")]
        LBF = 80,

        /// <summary>
        /// Enum LMK for value: LMK
        /// </summary>
        [EnumMember(Value = "LMK")]
        LMK = 81,

        /// <summary>
        /// Enum LOT for value: LOT
        /// </summary>
        [EnumMember(Value = "LOT")]
        LOT = 82,

        /// <summary>
        /// Enum LSX for value: LSX
        /// </summary>
        [EnumMember(Value = "LSX")]
        LSX = 83,

        /// <summary>
        /// Enum MKX for value: MKX
        /// </summary>
        [EnumMember(Value = "MKX")]
        MKX = 84,

        /// <summary>
        /// Enum MPX for value: MPX
        /// </summary>
        [EnumMember(Value = "MPX")]
        MPX = 85,

        /// <summary>
        /// Enum MQT for value: MQT
        /// </summary>
        [EnumMember(Value = "MQT")]
        MQT = 86,

        /// <summary>
        /// Enum OAX for value: OAX
        /// </summary>
        [EnumMember(Value = "OAX")]
        OAX = 87,

        /// <summary>
        /// Enum PAH for value: PAH
        /// </summary>
        [EnumMember(Value = "PAH")]
        PAH = 88,

        /// <summary>
        /// Enum PUB for value: PUB
        /// </summary>
        [EnumMember(Value = "PUB")]
        PUB = 89,

        /// <summary>
        /// Enum RIW for value: RIW
        /// </summary>
        [EnumMember(Value = "RIW")]
        RIW = 90,

        /// <summary>
        /// Enum SGF for value: SGF
        /// </summary>
        [EnumMember(Value = "SGF")]
        SGF = 91,

        /// <summary>
        /// Enum TOP for value: TOP
        /// </summary>
        [EnumMember(Value = "TOP")]
        TOP = 92,

        /// <summary>
        /// Enum UNR for value: UNR
        /// </summary>
        [EnumMember(Value = "UNR")]
        UNR = 93,

        /// <summary>
        /// Enum BOI for value: BOI
        /// </summary>
        [EnumMember(Value = "BOI")]
        BOI = 94,

        /// <summary>
        /// Enum BYZ for value: BYZ
        /// </summary>
        [EnumMember(Value = "BYZ")]
        BYZ = 95,

        /// <summary>
        /// Enum EKA for value: EKA
        /// </summary>
        [EnumMember(Value = "EKA")]
        EKA = 96,

        /// <summary>
        /// Enum FGZ for value: FGZ
        /// </summary>
        [EnumMember(Value = "FGZ")]
        FGZ = 97,

        /// <summary>
        /// Enum GGW for value: GGW
        /// </summary>
        [EnumMember(Value = "GGW")]
        GGW = 98,

        /// <summary>
        /// Enum HNX for value: HNX
        /// </summary>
        [EnumMember(Value = "HNX")]
        HNX = 99,

        /// <summary>
        /// Enum LKN for value: LKN
        /// </summary>
        [EnumMember(Value = "LKN")]
        LKN = 100,

        /// <summary>
        /// Enum LOX for value: LOX
        /// </summary>
        [EnumMember(Value = "LOX")]
        LOX = 101,

        /// <summary>
        /// Enum MFR for value: MFR
        /// </summary>
        [EnumMember(Value = "MFR")]
        MFR = 102,

        /// <summary>
        /// Enum MSO for value: MSO
        /// </summary>
        [EnumMember(Value = "MSO")]
        MSO = 103,

        /// <summary>
        /// Enum MTR for value: MTR
        /// </summary>
        [EnumMember(Value = "MTR")]
        MTR = 104,

        /// <summary>
        /// Enum OTX for value: OTX
        /// </summary>
        [EnumMember(Value = "OTX")]
        OTX = 105,

        /// <summary>
        /// Enum PDT for value: PDT
        /// </summary>
        [EnumMember(Value = "PDT")]
        PDT = 106,

        /// <summary>
        /// Enum PIH for value: PIH
        /// </summary>
        [EnumMember(Value = "PIH")]
        PIH = 107,

        /// <summary>
        /// Enum PQR for value: PQR
        /// </summary>
        [EnumMember(Value = "PQR")]
        PQR = 108,

        /// <summary>
        /// Enum PSR for value: PSR
        /// </summary>
        [EnumMember(Value = "PSR")]
        PSR = 109,

        /// <summary>
        /// Enum REV for value: REV
        /// </summary>
        [EnumMember(Value = "REV")]
        REV = 110,

        /// <summary>
        /// Enum SEW for value: SEW
        /// </summary>
        [EnumMember(Value = "SEW")]
        SEW = 111,

        /// <summary>
        /// Enum SGX for value: SGX
        /// </summary>
        [EnumMember(Value = "SGX")]
        SGX = 112,

        /// <summary>
        /// Enum SLC for value: SLC
        /// </summary>
        [EnumMember(Value = "SLC")]
        SLC = 113,

        /// <summary>
        /// Enum STO for value: STO
        /// </summary>
        [EnumMember(Value = "STO")]
        STO = 114,

        /// <summary>
        /// Enum TFX for value: TFX
        /// </summary>
        [EnumMember(Value = "TFX")]
        TFX = 115,

        /// <summary>
        /// Enum TWC for value: TWC
        /// </summary>
        [EnumMember(Value = "TWC")]
        TWC = 116,

        /// <summary>
        /// Enum VEF for value: VEF
        /// </summary>
        [EnumMember(Value = "VEF")]
        VEF = 117,

        /// <summary>
        /// Enum AER for value: AER
        /// </summary>
        [EnumMember(Value = "AER")]
        AER = 118,

        /// <summary>
        /// Enum AFC for value: AFC
        /// </summary>
        [EnumMember(Value = "AFC")]
        AFC = 119,

        /// <summary>
        /// Enum AFG for value: AFG
        /// </summary>
        [EnumMember(Value = "AFG")]
        AFG = 120,

        /// <summary>
        /// Enum AJK for value: AJK
        /// </summary>
        [EnumMember(Value = "AJK")]
        AJK = 121,

        /// <summary>
        /// Enum ALU for value: ALU
        /// </summary>
        [EnumMember(Value = "ALU")]
        ALU = 122,

        /// <summary>
        /// Enum GUM for value: GUM
        /// </summary>
        [EnumMember(Value = "GUM")]
        GUM = 123,

        /// <summary>
        /// Enum HPA for value: HPA
        /// </summary>
        [EnumMember(Value = "HPA")]
        HPA = 124,

        /// <summary>
        /// Enum HFO for value: HFO
        /// </summary>
        [EnumMember(Value = "HFO")]
        HFO = 125,

        /// <summary>
        /// Enum PPG for value: PPG
        /// </summary>
        [EnumMember(Value = "PPG")]
        PPG = 126,

        /// <summary>
        /// Enum STU for value: STU
        /// </summary>
        [EnumMember(Value = "STU")]
        STU = 127,

        /// <summary>
        /// Enum NH1 for value: NH1
        /// </summary>
        [EnumMember(Value = "NH1")]
        NH1 = 128,

        /// <summary>
        /// Enum NH2 for value: NH2
        /// </summary>
        [EnumMember(Value = "NH2")]
        NH2 = 129,

        /// <summary>
        /// Enum ONA for value: ONA
        /// </summary>
        [EnumMember(Value = "ONA")]
        ONA = 130,

        /// <summary>
        /// Enum ONP for value: ONP
        /// </summary>
        [EnumMember(Value = "ONP")]
        ONP = 131
    }

}
