/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// NWSOfficeId
    /// </summary>
    [JsonConverter(typeof(NWSOfficeIdJsonConverter))]
    [DataContract(Name = "NWSOfficeId")]
    public partial class NWSOfficeId : AbstractOpenAPISchema, IEquatable<NWSOfficeId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NWSOfficeId" /> class
        /// with the <see cref="NWSForecastOfficeId" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of NWSForecastOfficeId.</param>
        public NWSOfficeId(NWSForecastOfficeId actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NWSOfficeId" /> class
        /// with the <see cref="NWSRegionalHQId" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of NWSRegionalHQId.</param>
        public NWSOfficeId(NWSRegionalHQId actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NWSOfficeId" /> class
        /// with the <see cref="NWSNationalHQId" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of NWSNationalHQId.</param>
        public NWSOfficeId(NWSNationalHQId actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(NWSForecastOfficeId))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(NWSNationalHQId))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(NWSRegionalHQId))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: NWSForecastOfficeId, NWSNationalHQId, NWSRegionalHQId");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `NWSForecastOfficeId`. If the actual instance is not `NWSForecastOfficeId`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of NWSForecastOfficeId</returns>
        public NWSForecastOfficeId GetNWSForecastOfficeId()
        {
            return (NWSForecastOfficeId)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `NWSRegionalHQId`. If the actual instance is not `NWSRegionalHQId`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of NWSRegionalHQId</returns>
        public NWSRegionalHQId GetNWSRegionalHQId()
        {
            return (NWSRegionalHQId)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `NWSNationalHQId`. If the actual instance is not `NWSNationalHQId`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of NWSNationalHQId</returns>
        public NWSNationalHQId GetNWSNationalHQId()
        {
            return (NWSNationalHQId)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NWSOfficeId {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, NWSOfficeId.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of NWSOfficeId
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of NWSOfficeId</returns>
        public static NWSOfficeId FromJson(string jsonString)
        {
            NWSOfficeId newNWSOfficeId = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newNWSOfficeId;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(NWSForecastOfficeId).GetProperty("AdditionalProperties") == null)
                {
                    newNWSOfficeId = new NWSOfficeId(JsonConvert.DeserializeObject<NWSForecastOfficeId>(jsonString, NWSOfficeId.SerializerSettings));
                }
                else
                {
                    newNWSOfficeId = new NWSOfficeId(JsonConvert.DeserializeObject<NWSForecastOfficeId>(jsonString, NWSOfficeId.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("NWSForecastOfficeId");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into NWSForecastOfficeId: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(NWSNationalHQId).GetProperty("AdditionalProperties") == null)
                {
                    newNWSOfficeId = new NWSOfficeId(JsonConvert.DeserializeObject<NWSNationalHQId>(jsonString, NWSOfficeId.SerializerSettings));
                }
                else
                {
                    newNWSOfficeId = new NWSOfficeId(JsonConvert.DeserializeObject<NWSNationalHQId>(jsonString, NWSOfficeId.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("NWSNationalHQId");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into NWSNationalHQId: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(NWSRegionalHQId).GetProperty("AdditionalProperties") == null)
                {
                    newNWSOfficeId = new NWSOfficeId(JsonConvert.DeserializeObject<NWSRegionalHQId>(jsonString, NWSOfficeId.SerializerSettings));
                }
                else
                {
                    newNWSOfficeId = new NWSOfficeId(JsonConvert.DeserializeObject<NWSRegionalHQId>(jsonString, NWSOfficeId.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("NWSRegionalHQId");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into NWSRegionalHQId: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newNWSOfficeId;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NWSOfficeId);
        }

        /// <summary>
        /// Returns true if NWSOfficeId instances are equal
        /// </summary>
        /// <param name="input">Instance of NWSOfficeId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NWSOfficeId input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for NWSOfficeId
    /// </summary>
    public class NWSOfficeIdJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(NWSOfficeId).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return NWSOfficeId.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
