/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Three-letter identifier for a NWS Regional HQ.
    /// </summary>
    /// <value>Three-letter identifier for a NWS Regional HQ.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NWSRegionalHQId
    {
        /// <summary>
        /// Enum ARH for value: ARH
        /// </summary>
        [EnumMember(Value = "ARH")]
        ARH = 1,

        /// <summary>
        /// Enum CRH for value: CRH
        /// </summary>
        [EnumMember(Value = "CRH")]
        CRH = 2,

        /// <summary>
        /// Enum ERH for value: ERH
        /// </summary>
        [EnumMember(Value = "ERH")]
        ERH = 3,

        /// <summary>
        /// Enum PRH for value: PRH
        /// </summary>
        [EnumMember(Value = "PRH")]
        PRH = 4,

        /// <summary>
        /// Enum SRH for value: SRH
        /// </summary>
        [EnumMember(Value = "SRH")]
        SRH = 5,

        /// <summary>
        /// Enum WRH for value: WRH
        /// </summary>
        [EnumMember(Value = "WRH")]
        WRH = 6
    }

}
