/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Defines NWSZoneType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NWSZoneType
    {
        /// <summary>
        /// Enum Land for value: land
        /// </summary>
        [EnumMember(Value = "land")]
        Land = 1,

        /// <summary>
        /// Enum Marine for value: marine
        /// </summary>
        [EnumMember(Value = "marine")]
        Marine = 2,

        /// <summary>
        /// Enum Forecast for value: forecast
        /// </summary>
        [EnumMember(Value = "forecast")]
        Forecast = 3,

        /// <summary>
        /// Enum Public for value: public
        /// </summary>
        [EnumMember(Value = "public")]
        Public = 4,

        /// <summary>
        /// Enum Coastal for value: coastal
        /// </summary>
        [EnumMember(Value = "coastal")]
        Coastal = 5,

        /// <summary>
        /// Enum Offshore for value: offshore
        /// </summary>
        [EnumMember(Value = "offshore")]
        Offshore = 6,

        /// <summary>
        /// Enum Fire for value: fire
        /// </summary>
        [EnumMember(Value = "fire")]
        Fire = 7,

        /// <summary>
        /// Enum County for value: county
        /// </summary>
        [EnumMember(Value = "county")]
        County = 8
    }

}
