/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// RegionCode
    /// </summary>
    [JsonConverter(typeof(RegionCodeJsonConverter))]
    [DataContract(Name = "RegionCode")]
    public partial class RegionCode : AbstractOpenAPISchema, IEquatable<RegionCode>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegionCode" /> class
        /// with the <see cref="LandRegionCode" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LandRegionCode.</param>
        public RegionCode(LandRegionCode actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionCode" /> class
        /// with the <see cref="MarineRegionCode" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarineRegionCode.</param>
        public RegionCode(MarineRegionCode actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(LandRegionCode))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarineRegionCode))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: LandRegionCode, MarineRegionCode");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `LandRegionCode`. If the actual instance is not `LandRegionCode`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LandRegionCode</returns>
        public LandRegionCode GetLandRegionCode()
        {
            return (LandRegionCode)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarineRegionCode`. If the actual instance is not `MarineRegionCode`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarineRegionCode</returns>
        public MarineRegionCode GetMarineRegionCode()
        {
            return (MarineRegionCode)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegionCode {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, RegionCode.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of RegionCode
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of RegionCode</returns>
        public static RegionCode FromJson(string jsonString)
        {
            RegionCode newRegionCode = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newRegionCode;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(LandRegionCode).GetProperty("AdditionalProperties") == null)
                {
                    newRegionCode = new RegionCode(JsonConvert.DeserializeObject<LandRegionCode>(jsonString, RegionCode.SerializerSettings));
                }
                else
                {
                    newRegionCode = new RegionCode(JsonConvert.DeserializeObject<LandRegionCode>(jsonString, RegionCode.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("LandRegionCode");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LandRegionCode: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarineRegionCode).GetProperty("AdditionalProperties") == null)
                {
                    newRegionCode = new RegionCode(JsonConvert.DeserializeObject<MarineRegionCode>(jsonString, RegionCode.SerializerSettings));
                }
                else
                {
                    newRegionCode = new RegionCode(JsonConvert.DeserializeObject<MarineRegionCode>(jsonString, RegionCode.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarineRegionCode");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarineRegionCode: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newRegionCode;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RegionCode);
        }

        /// <summary>
        /// Returns true if RegionCode instances are equal
        /// </summary>
        /// <param name="input">Instance of RegionCode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegionCode input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for RegionCode
    /// </summary>
    public class RegionCodeJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(RegionCode).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return RegionCode.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
