/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// Defines StateTerritoryCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StateTerritoryCode
    {
        /// <summary>
        /// Enum AL for value: AL
        /// </summary>
        [EnumMember(Value = "AL")]
        AL = 1,

        /// <summary>
        /// Enum AK for value: AK
        /// </summary>
        [EnumMember(Value = "AK")]
        AK = 2,

        /// <summary>
        /// Enum AS for value: AS
        /// </summary>
        [EnumMember(Value = "AS")]
        AS = 3,

        /// <summary>
        /// Enum AR for value: AR
        /// </summary>
        [EnumMember(Value = "AR")]
        AR = 4,

        /// <summary>
        /// Enum AZ for value: AZ
        /// </summary>
        [EnumMember(Value = "AZ")]
        AZ = 5,

        /// <summary>
        /// Enum CA for value: CA
        /// </summary>
        [EnumMember(Value = "CA")]
        CA = 6,

        /// <summary>
        /// Enum CO for value: CO
        /// </summary>
        [EnumMember(Value = "CO")]
        CO = 7,

        /// <summary>
        /// Enum CT for value: CT
        /// </summary>
        [EnumMember(Value = "CT")]
        CT = 8,

        /// <summary>
        /// Enum DE for value: DE
        /// </summary>
        [EnumMember(Value = "DE")]
        DE = 9,

        /// <summary>
        /// Enum DC for value: DC
        /// </summary>
        [EnumMember(Value = "DC")]
        DC = 10,

        /// <summary>
        /// Enum FL for value: FL
        /// </summary>
        [EnumMember(Value = "FL")]
        FL = 11,

        /// <summary>
        /// Enum GA for value: GA
        /// </summary>
        [EnumMember(Value = "GA")]
        GA = 12,

        /// <summary>
        /// Enum GU for value: GU
        /// </summary>
        [EnumMember(Value = "GU")]
        GU = 13,

        /// <summary>
        /// Enum HI for value: HI
        /// </summary>
        [EnumMember(Value = "HI")]
        HI = 14,

        /// <summary>
        /// Enum ID for value: ID
        /// </summary>
        [EnumMember(Value = "ID")]
        ID = 15,

        /// <summary>
        /// Enum IL for value: IL
        /// </summary>
        [EnumMember(Value = "IL")]
        IL = 16,

        /// <summary>
        /// Enum IN for value: IN
        /// </summary>
        [EnumMember(Value = "IN")]
        IN = 17,

        /// <summary>
        /// Enum IA for value: IA
        /// </summary>
        [EnumMember(Value = "IA")]
        IA = 18,

        /// <summary>
        /// Enum KS for value: KS
        /// </summary>
        [EnumMember(Value = "KS")]
        KS = 19,

        /// <summary>
        /// Enum KY for value: KY
        /// </summary>
        [EnumMember(Value = "KY")]
        KY = 20,

        /// <summary>
        /// Enum LA for value: LA
        /// </summary>
        [EnumMember(Value = "LA")]
        LA = 21,

        /// <summary>
        /// Enum ME for value: ME
        /// </summary>
        [EnumMember(Value = "ME")]
        ME = 22,

        /// <summary>
        /// Enum MD for value: MD
        /// </summary>
        [EnumMember(Value = "MD")]
        MD = 23,

        /// <summary>
        /// Enum MA for value: MA
        /// </summary>
        [EnumMember(Value = "MA")]
        MA = 24,

        /// <summary>
        /// Enum MI for value: MI
        /// </summary>
        [EnumMember(Value = "MI")]
        MI = 25,

        /// <summary>
        /// Enum MN for value: MN
        /// </summary>
        [EnumMember(Value = "MN")]
        MN = 26,

        /// <summary>
        /// Enum MS for value: MS
        /// </summary>
        [EnumMember(Value = "MS")]
        MS = 27,

        /// <summary>
        /// Enum MO for value: MO
        /// </summary>
        [EnumMember(Value = "MO")]
        MO = 28,

        /// <summary>
        /// Enum MT for value: MT
        /// </summary>
        [EnumMember(Value = "MT")]
        MT = 29,

        /// <summary>
        /// Enum NE for value: NE
        /// </summary>
        [EnumMember(Value = "NE")]
        NE = 30,

        /// <summary>
        /// Enum NV for value: NV
        /// </summary>
        [EnumMember(Value = "NV")]
        NV = 31,

        /// <summary>
        /// Enum NH for value: NH
        /// </summary>
        [EnumMember(Value = "NH")]
        NH = 32,

        /// <summary>
        /// Enum NJ for value: NJ
        /// </summary>
        [EnumMember(Value = "NJ")]
        NJ = 33,

        /// <summary>
        /// Enum NM for value: NM
        /// </summary>
        [EnumMember(Value = "NM")]
        NM = 34,

        /// <summary>
        /// Enum NY for value: NY
        /// </summary>
        [EnumMember(Value = "NY")]
        NY = 35,

        /// <summary>
        /// Enum NC for value: NC
        /// </summary>
        [EnumMember(Value = "NC")]
        NC = 36,

        /// <summary>
        /// Enum ND for value: ND
        /// </summary>
        [EnumMember(Value = "ND")]
        ND = 37,

        /// <summary>
        /// Enum OH for value: OH
        /// </summary>
        [EnumMember(Value = "OH")]
        OH = 38,

        /// <summary>
        /// Enum OK for value: OK
        /// </summary>
        [EnumMember(Value = "OK")]
        OK = 39,

        /// <summary>
        /// Enum OR for value: OR
        /// </summary>
        [EnumMember(Value = "OR")]
        OR = 40,

        /// <summary>
        /// Enum PA for value: PA
        /// </summary>
        [EnumMember(Value = "PA")]
        PA = 41,

        /// <summary>
        /// Enum PR for value: PR
        /// </summary>
        [EnumMember(Value = "PR")]
        PR = 42,

        /// <summary>
        /// Enum RI for value: RI
        /// </summary>
        [EnumMember(Value = "RI")]
        RI = 43,

        /// <summary>
        /// Enum SC for value: SC
        /// </summary>
        [EnumMember(Value = "SC")]
        SC = 44,

        /// <summary>
        /// Enum SD for value: SD
        /// </summary>
        [EnumMember(Value = "SD")]
        SD = 45,

        /// <summary>
        /// Enum TN for value: TN
        /// </summary>
        [EnumMember(Value = "TN")]
        TN = 46,

        /// <summary>
        /// Enum TX for value: TX
        /// </summary>
        [EnumMember(Value = "TX")]
        TX = 47,

        /// <summary>
        /// Enum UT for value: UT
        /// </summary>
        [EnumMember(Value = "UT")]
        UT = 48,

        /// <summary>
        /// Enum VT for value: VT
        /// </summary>
        [EnumMember(Value = "VT")]
        VT = 49,

        /// <summary>
        /// Enum VI for value: VI
        /// </summary>
        [EnumMember(Value = "VI")]
        VI = 50,

        /// <summary>
        /// Enum VA for value: VA
        /// </summary>
        [EnumMember(Value = "VA")]
        VA = 51,

        /// <summary>
        /// Enum WA for value: WA
        /// </summary>
        [EnumMember(Value = "WA")]
        WA = 52,

        /// <summary>
        /// Enum WV for value: WV
        /// </summary>
        [EnumMember(Value = "WV")]
        WV = 53,

        /// <summary>
        /// Enum WI for value: WI
        /// </summary>
        [EnumMember(Value = "WI")]
        WI = 54,

        /// <summary>
        /// Enum WY for value: WY
        /// </summary>
        [EnumMember(Value = "WY")]
        WY = 55,

        /// <summary>
        /// Enum MP for value: MP
        /// </summary>
        [EnumMember(Value = "MP")]
        MP = 56,

        /// <summary>
        /// Enum PW for value: PW
        /// </summary>
        [EnumMember(Value = "PW")]
        PW = 57,

        /// <summary>
        /// Enum FM for value: FM
        /// </summary>
        [EnumMember(Value = "FM")]
        FM = 58,

        /// <summary>
        /// Enum MH for value: MH
        /// </summary>
        [EnumMember(Value = "MH")]
        MH = 59
    }

}
