/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace WeatherGov.Wrapper.Model
{
    /// <summary>
    /// TextProductTypeCollectionGraphInner
    /// </summary>
    [DataContract(Name = "TextProductTypeCollection__graph_inner")]
    public partial class TextProductTypeCollectionGraphInner : IEquatable<TextProductTypeCollectionGraphInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextProductTypeCollectionGraphInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TextProductTypeCollectionGraphInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TextProductTypeCollectionGraphInner" /> class.
        /// </summary>
        /// <param name="productCode">productCode (required).</param>
        /// <param name="productName">productName (required).</param>
        public TextProductTypeCollectionGraphInner(string productCode = default(string), string productName = default(string))
        {
            // to ensure "productCode" is required (not null)
            if (productCode == null)
            {
                throw new ArgumentNullException("productCode is a required property for TextProductTypeCollectionGraphInner and cannot be null");
            }
            this.ProductCode = productCode;
            // to ensure "productName" is required (not null)
            if (productName == null)
            {
                throw new ArgumentNullException("productName is a required property for TextProductTypeCollectionGraphInner and cannot be null");
            }
            this.ProductName = productName;
        }

        /// <summary>
        /// Gets or Sets ProductCode
        /// </summary>
        [DataMember(Name = "productCode", IsRequired = true, EmitDefaultValue = true)]
        public string ProductCode { get; set; }

        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name = "productName", IsRequired = true, EmitDefaultValue = true)]
        public string ProductName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TextProductTypeCollectionGraphInner {\n");
            sb.Append("  ProductCode: ").Append(ProductCode).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TextProductTypeCollectionGraphInner);
        }

        /// <summary>
        /// Returns true if TextProductTypeCollectionGraphInner instances are equal
        /// </summary>
        /// <param name="input">Instance of TextProductTypeCollectionGraphInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TextProductTypeCollectionGraphInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ProductCode == input.ProductCode ||
                    (this.ProductCode != null &&
                    this.ProductCode.Equals(input.ProductCode))
                ) && 
                (
                    this.ProductName == input.ProductName ||
                    (this.ProductName != null &&
                    this.ProductName.Equals(input.ProductName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductCode != null)
                {
                    hashCode = (hashCode * 59) + this.ProductCode.GetHashCode();
                }
                if (this.ProductName != null)
                {
                    hashCode = (hashCode * 59) + this.ProductName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
