/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AlertStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlertStatus
        //private AlertStatus instance;

        public AlertStatusTests()
        {
            // TODO uncomment below to create an instance of AlertStatus
            //instance = new AlertStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertStatus
        /// </summary>
        [Fact]
        public void AlertStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlertStatus
            //Assert.IsType<AlertStatus>(instance);
        }
    }
}
