/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AlertAtomEntryAuthor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertAtomEntryAuthorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlertAtomEntryAuthor
        //private AlertAtomEntryAuthor instance;

        public AlertAtomEntryAuthorTests()
        {
            // TODO uncomment below to create an instance of AlertAtomEntryAuthor
            //instance = new AlertAtomEntryAuthor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertAtomEntryAuthor
        /// </summary>
        [Fact]
        public void AlertAtomEntryAuthorInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlertAtomEntryAuthor
            //Assert.IsType<AlertAtomEntryAuthor>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
