/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AlertSeverity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertSeverityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlertSeverity
        //private AlertSeverity instance;

        public AlertSeverityTests()
        {
            // TODO uncomment below to create an instance of AlertSeverity
            //instance = new AlertSeverity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertSeverity
        /// </summary>
        [Fact]
        public void AlertSeverityInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlertSeverity
            //Assert.IsType<AlertSeverity>(instance);
        }
    }
}
