/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GeoJSONMultiLineString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoJSONMultiLineStringTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoJSONMultiLineString
        //private GeoJSONMultiLineString instance;

        public GeoJSONMultiLineStringTests()
        {
            // TODO uncomment below to create an instance of GeoJSONMultiLineString
            //instance = new GeoJSONMultiLineString();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoJSONMultiLineString
        /// </summary>
        [Fact]
        public void GeoJSONMultiLineStringInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoJSONMultiLineString
            //Assert.IsType<GeoJSONMultiLineString>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Coordinates'
        /// </summary>
        [Fact]
        public void CoordinatesTest()
        {
            // TODO unit test for the property 'Coordinates'
        }

        /// <summary>
        /// Test the property 'Bbox'
        /// </summary>
        [Fact]
        public void BboxTest()
        {
            // TODO unit test for the property 'Bbox'
        }
    }
}
