/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Glossary200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Glossary200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Glossary200Response
        //private Glossary200Response instance;

        public Glossary200ResponseTests()
        {
            // TODO uncomment below to create an instance of Glossary200Response
            //instance = new Glossary200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Glossary200Response
        /// </summary>
        [Fact]
        public void Glossary200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Glossary200Response
            //Assert.IsType<Glossary200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Glossary'
        /// </summary>
        [Fact]
        public void GlossaryTest()
        {
            // TODO unit test for the property 'Glossary'
        }
    }
}
