/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GridpointQuantitativeValueLayer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridpointQuantitativeValueLayerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridpointQuantitativeValueLayer
        //private GridpointQuantitativeValueLayer instance;

        public GridpointQuantitativeValueLayerTests()
        {
            // TODO uncomment below to create an instance of GridpointQuantitativeValueLayer
            //instance = new GridpointQuantitativeValueLayer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridpointQuantitativeValueLayer
        /// </summary>
        [Fact]
        public void GridpointQuantitativeValueLayerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridpointQuantitativeValueLayer
            //Assert.IsType<GridpointQuantitativeValueLayer>(instance);
        }

        /// <summary>
        /// Test the property 'Uom'
        /// </summary>
        [Fact]
        public void UomTest()
        {
            // TODO unit test for the property 'Uom'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
