/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GridpointWeather
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridpointWeatherTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridpointWeather
        //private GridpointWeather instance;

        public GridpointWeatherTests()
        {
            // TODO uncomment below to create an instance of GridpointWeather
            //instance = new GridpointWeather();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridpointWeather
        /// </summary>
        [Fact]
        public void GridpointWeatherInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridpointWeather
            //Assert.IsType<GridpointWeather>(instance);
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
