/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GridpointHazardsValuesInnerValueInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridpointHazardsValuesInnerValueInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridpointHazardsValuesInnerValueInner
        //private GridpointHazardsValuesInnerValueInner instance;

        public GridpointHazardsValuesInnerValueInnerTests()
        {
            // TODO uncomment below to create an instance of GridpointHazardsValuesInnerValueInner
            //instance = new GridpointHazardsValuesInnerValueInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridpointHazardsValuesInnerValueInner
        /// </summary>
        [Fact]
        public void GridpointHazardsValuesInnerValueInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridpointHazardsValuesInnerValueInner
            //Assert.IsType<GridpointHazardsValuesInnerValueInner>(instance);
        }

        /// <summary>
        /// Test the property 'Phenomenon'
        /// </summary>
        [Fact]
        public void PhenomenonTest()
        {
            // TODO unit test for the property 'Phenomenon'
        }

        /// <summary>
        /// Test the property 'Significance'
        /// </summary>
        [Fact]
        public void SignificanceTest()
        {
            // TODO unit test for the property 'Significance'
        }

        /// <summary>
        /// Test the property 'EventNumber'
        /// </summary>
        [Fact]
        public void EventNumberTest()
        {
            // TODO unit test for the property 'EventNumber'
        }
    }
}
