/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GridpointForecast
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridpointForecastTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridpointForecast
        //private GridpointForecast instance;

        public GridpointForecastTests()
        {
            // TODO uncomment below to create an instance of GridpointForecast
            //instance = new GridpointForecast();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridpointForecast
        /// </summary>
        [Fact]
        public void GridpointForecastInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridpointForecast
            //Assert.IsType<GridpointForecast>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Fact]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'ForecastGenerator'
        /// </summary>
        [Fact]
        public void ForecastGeneratorTest()
        {
            // TODO unit test for the property 'ForecastGenerator'
        }

        /// <summary>
        /// Test the property 'GeneratedAt'
        /// </summary>
        [Fact]
        public void GeneratedAtTest()
        {
            // TODO unit test for the property 'GeneratedAt'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'ValidTimes'
        /// </summary>
        [Fact]
        public void ValidTimesTest()
        {
            // TODO unit test for the property 'ValidTimes'
        }

        /// <summary>
        /// Test the property 'Elevation'
        /// </summary>
        [Fact]
        public void ElevationTest()
        {
            // TODO unit test for the property 'Elevation'
        }

        /// <summary>
        /// Test the property 'Periods'
        /// </summary>
        [Fact]
        public void PeriodsTest()
        {
            // TODO unit test for the property 'Periods'
        }
    }
}
