/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GridpointHazards
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridpointHazardsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridpointHazards
        //private GridpointHazards instance;

        public GridpointHazardsTests()
        {
            // TODO uncomment below to create an instance of GridpointHazards
            //instance = new GridpointHazards();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridpointHazards
        /// </summary>
        [Fact]
        public void GridpointHazardsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridpointHazards
            //Assert.IsType<GridpointHazards>(instance);
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
