/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GridpointForecastPeriodWindGust
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridpointForecastPeriodWindGustTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridpointForecastPeriodWindGust
        //private GridpointForecastPeriodWindGust instance;

        public GridpointForecastPeriodWindGustTests()
        {
            // TODO uncomment below to create an instance of GridpointForecastPeriodWindGust
            //instance = new GridpointForecastPeriodWindGust();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridpointForecastPeriodWindGust
        /// </summary>
        [Fact]
        public void GridpointForecastPeriodWindGustInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridpointForecastPeriodWindGust
            //Assert.IsType<GridpointForecastPeriodWindGust>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'MaxValue'
        /// </summary>
        [Fact]
        public void MaxValueTest()
        {
            // TODO unit test for the property 'MaxValue'
        }

        /// <summary>
        /// Test the property 'MinValue'
        /// </summary>
        [Fact]
        public void MinValueTest()
        {
            // TODO unit test for the property 'MinValue'
        }

        /// <summary>
        /// Test the property 'UnitCode'
        /// </summary>
        [Fact]
        public void UnitCodeTest()
        {
            // TODO unit test for the property 'UnitCode'
        }

        /// <summary>
        /// Test the property 'QualityControl'
        /// </summary>
        [Fact]
        public void QualityControlTest()
        {
            // TODO unit test for the property 'QualityControl'
        }
    }
}
