/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IconsSummary200ResponseIconsValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IconsSummary200ResponseIconsValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IconsSummary200ResponseIconsValue
        //private IconsSummary200ResponseIconsValue instance;

        public IconsSummary200ResponseIconsValueTests()
        {
            // TODO uncomment below to create an instance of IconsSummary200ResponseIconsValue
            //instance = new IconsSummary200ResponseIconsValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IconsSummary200ResponseIconsValue
        /// </summary>
        [Fact]
        public void IconsSummary200ResponseIconsValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" IconsSummary200ResponseIconsValue
            //Assert.IsType<IconsSummary200ResponseIconsValue>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
