/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JsonLdContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonLdContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonLdContext
        //private JsonLdContext instance;

        public JsonLdContextTests()
        {
            // TODO uncomment below to create an instance of JsonLdContext
            //instance = new JsonLdContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonLdContext
        /// </summary>
        [Fact]
        public void JsonLdContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonLdContext
            //Assert.IsType<JsonLdContext>(instance);
        }
    }
}
