/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NWSForecastOfficeId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NWSForecastOfficeIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NWSForecastOfficeId
        //private NWSForecastOfficeId instance;

        public NWSForecastOfficeIdTests()
        {
            // TODO uncomment below to create an instance of NWSForecastOfficeId
            //instance = new NWSForecastOfficeId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NWSForecastOfficeId
        /// </summary>
        [Fact]
        public void NWSForecastOfficeIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" NWSForecastOfficeId
            //Assert.IsType<NWSForecastOfficeId>(instance);
        }
    }
}
