/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NWSOfficeId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NWSOfficeIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NWSOfficeId
        //private NWSOfficeId instance;

        public NWSOfficeIdTests()
        {
            // TODO uncomment below to create an instance of NWSOfficeId
            //instance = new NWSOfficeId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NWSOfficeId
        /// </summary>
        [Fact]
        public void NWSOfficeIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" NWSOfficeId
            //Assert.IsType<NWSOfficeId>(instance);
        }
    }
}
