/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ObservationStation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObservationStationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObservationStation
        //private ObservationStation instance;

        public ObservationStationTests()
        {
            // TODO uncomment below to create an instance of ObservationStation
            //instance = new ObservationStation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObservationStation
        /// </summary>
        [Fact]
        public void ObservationStationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObservationStation
            //Assert.IsType<ObservationStation>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Fact]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Elevation'
        /// </summary>
        [Fact]
        public void ElevationTest()
        {
            // TODO unit test for the property 'Elevation'
        }

        /// <summary>
        /// Test the property 'StationIdentifier'
        /// </summary>
        [Fact]
        public void StationIdentifierTest()
        {
            // TODO unit test for the property 'StationIdentifier'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Fact]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }

        /// <summary>
        /// Test the property 'Forecast'
        /// </summary>
        [Fact]
        public void ForecastTest()
        {
            // TODO unit test for the property 'Forecast'
        }

        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Fact]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }

        /// <summary>
        /// Test the property 'FireWeatherZone'
        /// </summary>
        [Fact]
        public void FireWeatherZoneTest()
        {
            // TODO unit test for the property 'FireWeatherZone'
        }
    }
}
