/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ObservationStationCollectionGeoJson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObservationStationCollectionGeoJsonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObservationStationCollectionGeoJson
        //private ObservationStationCollectionGeoJson instance;

        public ObservationStationCollectionGeoJsonTests()
        {
            // TODO uncomment below to create an instance of ObservationStationCollectionGeoJson
            //instance = new ObservationStationCollectionGeoJson();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObservationStationCollectionGeoJson
        /// </summary>
        [Fact]
        public void ObservationStationCollectionGeoJsonInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObservationStationCollectionGeoJson
            //Assert.IsType<ObservationStationCollectionGeoJson>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

        /// <summary>
        /// Test the property 'ObservationStations'
        /// </summary>
        [Fact]
        public void ObservationStationsTest()
        {
            // TODO unit test for the property 'ObservationStations'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
