/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ObservationStationCollectionJsonLd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObservationStationCollectionJsonLdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObservationStationCollectionJsonLd
        //private ObservationStationCollectionJsonLd instance;

        public ObservationStationCollectionJsonLdTests()
        {
            // TODO uncomment below to create an instance of ObservationStationCollectionJsonLd
            //instance = new ObservationStationCollectionJsonLd();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObservationStationCollectionJsonLd
        /// </summary>
        [Fact]
        public void ObservationStationCollectionJsonLdInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObservationStationCollectionJsonLd
            //Assert.IsType<ObservationStationCollectionJsonLd>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Graph'
        /// </summary>
        [Fact]
        public void GraphTest()
        {
            // TODO unit test for the property 'Graph'
        }

        /// <summary>
        /// Test the property 'ObservationStations'
        /// </summary>
        [Fact]
        public void ObservationStationsTest()
        {
            // TODO unit test for the property 'ObservationStations'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
