/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ObservationCollectionJsonLd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObservationCollectionJsonLdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObservationCollectionJsonLd
        //private ObservationCollectionJsonLd instance;

        public ObservationCollectionJsonLdTests()
        {
            // TODO uncomment below to create an instance of ObservationCollectionJsonLd
            //instance = new ObservationCollectionJsonLd();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObservationCollectionJsonLd
        /// </summary>
        [Fact]
        public void ObservationCollectionJsonLdInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObservationCollectionJsonLd
            //Assert.IsType<ObservationCollectionJsonLd>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Graph'
        /// </summary>
        [Fact]
        public void GraphTest()
        {
            // TODO unit test for the property 'Graph'
        }
    }
}
