/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RegionCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegionCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegionCode
        //private RegionCode instance;

        public RegionCodeTests()
        {
            // TODO uncomment below to create an instance of RegionCode
            //instance = new RegionCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegionCode
        /// </summary>
        [Fact]
        public void RegionCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegionCode
            //Assert.IsType<RegionCode>(instance);
        }
    }
}
