/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RelativeLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RelativeLocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RelativeLocation
        //private RelativeLocation instance;

        public RelativeLocationTests()
        {
            // TODO uncomment below to create an instance of RelativeLocation
            //instance = new RelativeLocation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RelativeLocation
        /// </summary>
        [Fact]
        public void RelativeLocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" RelativeLocation
            //Assert.IsType<RelativeLocation>(instance);
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Fact]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }

        /// <summary>
        /// Test the property 'Bearing'
        /// </summary>
        [Fact]
        public void BearingTest()
        {
            // TODO unit test for the property 'Bearing'
        }
    }
}
