/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TextProductLocationCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TextProductLocationCollectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TextProductLocationCollection
        //private TextProductLocationCollection instance;

        public TextProductLocationCollectionTests()
        {
            // TODO uncomment below to create an instance of TextProductLocationCollection
            //instance = new TextProductLocationCollection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TextProductLocationCollection
        /// </summary>
        [Fact]
        public void TextProductLocationCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" TextProductLocationCollection
            //Assert.IsType<TextProductLocationCollection>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Fact]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }
    }
}
