/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TextProductTypeCollectionGraphInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TextProductTypeCollectionGraphInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TextProductTypeCollectionGraphInner
        //private TextProductTypeCollectionGraphInner instance;

        public TextProductTypeCollectionGraphInnerTests()
        {
            // TODO uncomment below to create an instance of TextProductTypeCollectionGraphInner
            //instance = new TextProductTypeCollectionGraphInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TextProductTypeCollectionGraphInner
        /// </summary>
        [Fact]
        public void TextProductTypeCollectionGraphInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" TextProductTypeCollectionGraphInner
            //Assert.IsType<TextProductTypeCollectionGraphInner>(instance);
        }

        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Fact]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }

        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Fact]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
    }
}
