/*
 * weather.gov API
 *
 * weather.gov API
 *
 * The version of the OpenAPI document: 1.11.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ZoneState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ZoneStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ZoneState
        //private ZoneState instance;

        public ZoneStateTests()
        {
            // TODO uncomment below to create an instance of ZoneState
            //instance = new ZoneState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ZoneState
        /// </summary>
        [Fact]
        public void ZoneStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ZoneState
            //Assert.IsType<ZoneState>(instance);
        }
    }
}
